### PR TITLE
Processing data in models

### PR DESCRIPTION
**Pull request by principles31**
# Blog App - processing data in models:
- The goal of this project is to set up our models. To start with, we have tables for Users, Posts, Comments, and Likes, which means we need a model for each one. You've already set the foreign key in the table schema but be sure to write it here too!
## The following were implemented in this **PR** as project requirements:

- Created at least one user by running the following code:

   - first_user = User.create(name: 'Tom', photo: 'https://unsplash.com/photos/F_-0BxGuVvo', bio: 'Teacher from Mexico.')
   - second_user = User.create(name: 'Lilly', photo: 'https://unsplash.com/photos/F_-0BxGuVvo', bio: 'Teacher from Poland.')
>  Created at least 4 posts written by one of the users you created by running the following code:

   - first_post = Post.create(author: first_user, title: 'Hello', text: 'This is my first post')
> Created at least 6 posts comments for one of the posts you created by running the following code:

   - Comment.create(post: first_post, author: second_user, text: 'Hi Tom!' )
> Created custom methods for models to include some additional methods.

> Users

- A method that returns the 3 most recent posts for a given user.
> Posts

- A method that updates the posts counter for a user.
- A method which returns the 5 most recent comments for a given post.
> Comments

- A method that updates the comments counter for a post.
> Likes

- A method that updates the likes counter for a post.

### CODE REVIEW

**Review by phelian23 — COMMENTED** [review]
Hi @principles31,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted your project with the wrong link...You submitted processing data in modes in the link for validations and model specs

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by principles31** [comment]
- NB
- I mistakenly requested for review with this branch for another project (validation and model spc)which is yet to be done

**Review by AshakaE — APPROVED** [review]
Hi @principles31 🙋‍♂️ , 

### Highlights ✨ 

- Code base looks clean 👍 
- Pull request 👌 
- Git flow ✅ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Proceed to the next level 👏 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by principles31** [comment]
- Please anyone who claims this branch for **Validation and models specs project** for review should abort it. Thank you

**Comment by principles31** [comment]
@AshakaE Thank you for your quick response, keep it up.

**Pull request merged**
