### PR TITLE
Data model

### PR DESCRIPTION
**Pull request by principles31**
# Blog app - creating a data model
- This project requires to use migration files to build your schema.
>  The following were implemented in this **PR** as the project requirements:
- Create a new app. Give it a meaningful name.
- Initialize your project with Git.
- Make sure that your project has Postgres database set up.
- Build your project schema.
   > Create and run the necessary migration files.
   > Table and column names should match the ERD diagram.
 - note: photo for users table should be a link to an image
    > Foreign keys should be included.
    > All columns that are foreign keys should have a corresponding index.

### CODE REVIEW

**Review by dasileker — CHANGES_REQUESTED** [review]
### **Hi @principles31,** 

### **Good job so far!**
There are some issues that you still need to work on to go to the next project but you are almost there!

## **Highlights**
- PR is very good and full of info ✅.
- Commit messages are consistent ✅.

## Required Changes ♻️
_Check the comments under the review._
- Hello and nice work on adding the data_model but you forgot to add explicit details about the project in your readme file, please do so and ask for another review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by principles31** [comment]
@dasileker Thanks for your constructive feedback

**Comment by principles31** [comment]
> Hello and nice work on adding the data_model but you forgot to add explicit details about the project in your readme file, please do so and ask for another review.
- The above changes requested by the previous reviewer were implemented.

**Review by rloterh — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi Manuel,  

Your project is complete! There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉🌟 

## Highlights 👍
- Migration query properly implemented


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


**You can also consider:**
- I think it will be a good thing to change the header title Authors to Author, as this project is done solely. This will make your ReadMe appear more professional.


<br>
Keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by principles31** [comment]
@rloterh Thanks for the approval and the reminder.

**Pull request merged**
