### PR TITLE
Controllers

### PR DESCRIPTION
**Pull request by principles31**
# Blog app - controllers:
- In this project, you will create all controllers and views for your Blog app. As you won't be processing any data yet, you will add simple placeholders for your views with plain HTML.
> The following were implemented in this PR as the project requirements:
- For each URL I created:

> A route.
 > An action in the correct controller.
 > A view file.
- View files includes only placeholders written in plain HTML, e.g:

 > Here is a list of posts for a given user
- Added code to handle only the 4 required URLs.

### CODE REVIEW

**Review by omarsalem7 — CHANGES_REQUESTED** [review]
Hi @principles31 😊, 

Good job so far! 👏
You have done well reaching this point of the milestone, but there are some issues that you still need to work on to go to the next project but you are almost there! 

you-are-near

## Highlights
- There is no linter error present ✔️
- The Pull Request has a proper title and description. ✔️
- Correct git-flow ✔️

## Required Changes ♻️

- [x] Kindly add views for each route like in screenshots but it is just a plain html.
- [x] Also add nested routes for users and posts something like this:
```ruby
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show]
  end

``` 

_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by principles31** [comment]
- [x] Kindly add views for each route like in screenshots but it is just a plain html.
- [x]  Also add nested routes for users and posts something like this:
- [x] The above changes requested by the previous reviewer have been implemented.

**Comment by principles31** [comment]
@omarsalem7 Thank you for your feedback.

**Review by Munsa1 — APPROVED** [review]
Hi @principles31 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
:heavy_check_mark: Descriptive Readme
:heavy_check_mark: Passing Linters
:heavy_check_mark: Correct Gitflow

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by principles31** [comment]
@Munsa1 Thank you for your approval

**Pull request merged**
